### ISSUE TITLE
Missing Certain Weapons

### ISSUE THREAD

**Issue by AETHERNALITY** [LittleLightForDestiny/littlelight_wishlists#131]
With the latest update I've noticed that there are a few weapons missing:
- Word of Crota
- Updated Last Wish weapons
there could be a few more but those are the ones I noticed

**Comment by bill0042** [comment]
Word of Crota is very new and the manifest data that shows what perks can roll on it was just released today by Bungie. It will take some time for the new raid weapons to be evaluated and wishlists created. Pandapaxxy's wishlists for this season and the new raid should be finished in the next few days. His current wishlist already has the updated Last Wish weapons. When things get done depends on the curator, also.
